<a href="https://colab.research.google.com/github/joewebkid/deep_learning_summary/blob/main/additional_materials/%5Bhomework%5Dnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.49160631 0.62712942 0.64489308 ... 0.34274005 0.28356768 0.90747123]
 [0.04797162 0.43772548 0.78552957 ... 0.34052025 0.67648613 0.10751443]
 [0.43528449 0.2175656  0.98989156 ... 0.57807791 0.44537055 0.35032689]
 ...
 [0.09628013 0.68780627 0.02397    ... 0.31826211 0.1367672  0.62753657]
 [0.42618291 0.92539337 0.81388765 ... 0.14280957 0.17400498 0.66699837]
 [0.24470763 0.9200382  0.46217202 ... 0.64105839 0.74953087 0.47266469]]
[[0.80934315 0.18919808 0.83306395 ... 0.06811225 0.01585394 0.46950755]
 [0.92291472 0.84362653 0.47294737 ... 0.16810094 0.29303735 0.54023621]
 [0.65015882 0.81120685 0.27727824 ... 0.2095331  0.70220822 0.61297224]
 ...
 [0.16711293 0.58848097 0.55438869 ... 0.23719888 0.69533787 0.73044737]
 [0.38172037 0.20186295 0.87872067 ... 0.24214717 0.61370787 0.70235975]
 [0.15926373 0.03965502 0.45845594 ... 0.2173081  0.17075708 0.77233754]]


In [ ]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    size = len(a)
    result = [[0 for i in range(size)] for i in range(size)]

    for i in range(size):
      for j in range(size):       
          result[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(size))

    return result

In [ ]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return a.dot(b)

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.05 s, sys: 6.37 ms, total: 1.06 s
Wall time: 1.07 s


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 169 µs, sys: 0 ns, total: 169 µs
Wall time: 131 µs


In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.64648614 0.06419793 0.31839954] [0.95069026 0.2990459  0.04406345]


In [ ]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    size = len(a)
    result = 0

    for i in range(size):
      result += a[i]*b[i]
    return result

In [ ]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return np.vdot(a,b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 24 µs, sys: 4 µs, total: 28 µs
Wall time: 33.4 µs
CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 35.8 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
def diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    size = len(a)
    result = 0
    for i in range(size):
      for j in range(size):
        if i == j:
          if a[i,j]%2 == 0:
            result += a[i,j]
    return result


In [ ]:
def np_diag_2k(a):
  # a[(a%2 == 0) & (np.eye(len(a)) == 1)].sum()
  # result = np.trace(a*(a%2==0))
  # np.putmask(a, a % 2 == 1, [0])
  return sum(np.diagonal(a)[np.diagonal(a)%2 == 0])

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 1, 5, 9, 8],
       [5, 5, 1, 7, 5],
       [2, 6, 8, 4, 1],
       [4, 3, 3, 1, 7],
       [3, 6, 3, 3, 3]])

In [ ]:
%%time
# засечем время работы функции без NumPy
diag_2k(a)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 37 µs


14

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 78 µs, sys: 12 µs, total: 90 µs
Wall time: 94.9 µs


14

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [ ]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    result = np.cumsum(A, axis=-1)  
    return result

In [ ]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 76.8 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [3]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a = 1):
    
    # Ваш код здесь
    
    Y = np.zeros(X.shape[0])
    
    for i in range(X.shape[0]):        
        if i % 2 != 0:            
            Y[i] = a            
        else:                
            if X.shape[0] % 2 == 0:                
                Y[i] = X[X.shape[0] - i - 2] ** 3                
            else:                
                Y[i] = X[X.shape[0] - i - 1] ** 3
                    
    return Y

In [60]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    Y = np.copy(X) 
    Y[:, 1::2] = a
    Y[:,0::2] **= 3   
    Y[:,:] = Y[:,::-1] 

    # return np.append(X,Y,axis=1)
    # return np.hstack((X, Y[:,::-1]))
    return np.concatenate((X, Y), axis=1)

# X = np.array([[i for i in range(1, 10, 2)]])
# print(X[:,:])
# print(X[:,::-1])
# print(X.shape)
# np_transformation(X, 5)  

In [66]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 65 µs, sys: 10 µs, total: 75 µs
Wall time: 79.2 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [83]:
from itertools import groupby

def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    Keys = np.array([])
    Lens = np.array([])
    for key, group in groupby(X):
      li = list(group)
      Keys = np.append(Keys,key)
      Lens = np.append(Lens,len(li))

    return (Keys, Lens)

In [81]:

Keys = np.array([])
Lens = np.array([])
for key, group in groupby(X):
    li = list(group)
    Keys = np.append(Keys,key)
    Lens = np.append(Lens,len(li))
    # print('key {} has len {}: {}'.format(key, len(li), li))

(Keys, Lens)

(array([1., 2., 3., 1., 5., 2., 3.]), array([1., 2., 2., 2., 2., 1., 2.]))

In [73]:
# import numpy as np 
# def encode(a): 
#   b=np.copy(a) 
#   np.insert(b,0,0) 
#   np.delete(b, -1) 
#   c = a[a!=b] 
#   d = np.ones_like(c) 
#   j, cnt = 0,1 
#   for i in range(1, len(a)): 
#     if a[i]==c[j]: 
#       cnt+=1 
#       d[j]=cnt 
#     else: 
#       d[j]=cnt 
#       cnt=1 j+=1 
#   return (c, d)

In [88]:
def np_encode(a):
    mask = np.r_[True, a[:-1]!=a[1:], True]
    counts = np.diff(np.flatnonzero(mask))
    return (a[mask[:-1]], counts)

In [87]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 1.21 ms, sys: 0 ns, total: 1.21 ms
Wall time: 1.29 ms


In [89]:
%time x, num = encode(X)

CPU times: user 197 µs, sys: 862 µs, total: 1.06 ms
Wall time: 1.04 ms
