<a href="https://colab.research.google.com/github/joewebkid/deep_learning_summary/blob/main/additional_materials/numpy_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <center> Matrix Algebra with Numpy </center> ##

### What is a matrix? ###

A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. For example:

 ![](img/matrix.jpg)

This matrix is a $3\times 4$ (three-by-four) matrix because it has 3 rows and
4 columns.

### Matrices in Python ###

Python doesn't have a built-in type for matrices. However, we can treat list of a list as a matrix. For example:

In [ ]:
A = [[1, 4, 5, 12], 
     [-5, 8, 9, 0],
     [-6, 7, 11, 19]]

print("A =", A) 
print("A[0] =", A[0])  # 1st row. Note that the index starts from 0 but not 1.
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[0] = [1, 4, 5, 12]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 11]


In [ ]:
#Likewise, we can define a vector as a list.
vec_x = [2.0, 3.0, 5.0] # A row vector
print(vec_x)     
print(vec_x[0], vec_x[1] , vec_x[2])  # To access each component of the vecor.

[2.0, 3.0, 5.0]
2.0 3.0 5.0


We may use Python matrix for simple computational task, however, there is a better way of working with matrices in Python using [Numpy](https://docs.scipy.org/doc/numpy-1.10.1/user/whatisnumpy.html).

### NumPy Array ###

`NumPy` is a Python module that supports vectors and matrices in an optimized way. Using the built-in data structures of the Python programming language, we just implemented examples of vectors and matrices, but NumPy gives us a better way. Because NumPy is written in C code, it’s also incredibly fast to do:

Let's take some examples:

In [ ]:
import numpy as np

# A 1D array, shape-(3,)
vector1 = np.array([1,2,3]) 

# A 2D array, shape-(2,3)
matrix1 = np.array( [[0,4,1], [2,0,1]] ) 

# A 3D array, shape-(2, 3, 4): two two-dimensional arrays of shape 3×4
matrix2 = np.array([[[0, 1, -2, 3],
                     [2, 3, 0, 1],
                     [-1, 2, 4, 1]],
                    [[4, 5, 0, 2],
                     [6, 7, 0, 1],
                     [2, 1, 0, 8]]])

print(vector1, type(vector1), vector1.dtype, vector1.shape, '\n')
print(matrix1, type(matrix1), matrix1.dtype, matrix1.shape, '\n')
print(matrix2, type(matrix2), matrix2.dtype, matrix2.shape)

[1 2 3] <class 'numpy.ndarray'> int64 (3,) 

[[0 4 1]
 [2 0 1]] <class 'numpy.ndarray'> int64 (2, 3) 

[[[ 0  1 -2  3]
  [ 2  3  0  1]
  [-1  2  4  1]]

 [[ 4  5  0  2]
  [ 6  7  0  1]
  [ 2  1  0  8]]] <class 'numpy.ndarray'> int64 (2, 3, 4)


As you can see, NumPy's array class is called `ndarray`. Here, `np.array()` replaces the previous *Python Matrix* we used to represent these data structures.

### Array of integers, floats and complex Numbers ###

In [ ]:
B1 = np.array([[1, 2, 3], [3, 4, 5]])
print(B1)

B2 = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(B2)

B3 = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(B3)                                              # j = sqrt(-1)

a = np.array([1,2,3])
b = np.array([4,5,6])
B4 = a + 1j*b # Note that the imaginary part is `1j` but not 'j'
print(B4)
print(B4*(2+1j))

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]
[1.+4.j 2.+5.j 3.+6.j]
[-2. +9.j -1.+12.j  0.+15.j]


### Array of zeros and ones ###

In [ ]:
zeors_array = np.zeros( (2, 3) )
print(zeors_array)

ones_array = np.ones( (1, 5), dtype=np.int32 ) # specifying dtype
print(ones_array)      

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]]


Here, we have specified `dtype` to 32 bits (4 bytes). Hence, this array can take values from $-2^{31}$ to $2^{31}-1$.

### Manipulating arrays with **reshape()** ###

NumPy provides an assortment of functions that allow us manipulate the way that an array’s element can be accessed. These permit us to reshape an array, change its dimensionality, and swap the positions of its elements. 

A complete listing of the available array-manipulation functions can be found in the offocial Numpy documentation [Array manipulation routines](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html). Among these functions, the `reshape()` function is especially useful.

The `reshape()` function allows you to change the dimensionality and layout of a given array. Let’s take a shape-(6,) array, and reshape it to a shape-(2, 3) array:

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5])

# Reshape a shape-(6,) array into a shape-(2,3) array
x.reshape(2,3) # This doesn't cahnge 'x'
print('x = ', x, '\n', 'x_reshaped = ', x.reshape(2,3))

x =  [0 1 2 3 4 5] 
 x_reshaped =  [[0 1 2]
 [3 4 5]]


You can also conveniently reshape an array by “setting” its shape via assignment:

In [ ]:
# equivalent to: x = x.reshape(2, 3)
x.shape = (2, 3) #This change 'x'
print(x)

[[0 1 2]
 [3 4 5]]


Of course, the size the the initial array must match the size of the to-be reshaped array:

In [ ]:
# an array with 5 numbers are cannot be reshaped
# into a (3, 2) array, which needs 3*2=6 numbers.
np.array([0, 1, 2, 3, 4]).reshape(3, 2)

ValueError: cannot reshape array of size 5 into shape (3,2)

Multidimensional arrays can be reshaped too:

In [ ]:
# reshaping a multidimensional array
y = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

# reshape from (3, 4) to (2, 3, 2)
y.reshape(2, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

Because the size of an input array and the resulting reshaped array must agree, you can specify one of the dimension-sizes in the reshape function to be -1, and this will cue NumPy to compute that dimension’s size for you. For example, if you are reshaping a shape-(36,) array into a shape-(3, 4, 3) array. The following are valid:

In [ ]:
# Equivalent ways of specifying a reshape
# np.arange(36) produces the shape-(36,) array ([0, 1, 2, ..., 35])
np.arange(36).reshape(3, 4, 3)   # (36,) --reshape--> (3, 4, 3)
np.arange(36).reshape(3, 4, -1)  # NumPy replaces -1 with 36/(3*4) -> 3
np.arange(36).reshape(3, -1, 3)  # NumPy replaces -1 with 36/(3*3) -> 4
np.arange(36).reshape(-1, 4, 3)  # NumPy replaces -1 with 36/(3*4) -> 3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

You can use -1 to specify only one dimension:

In [ ]:
np.arange(36).reshape(3, -1, -1)  # this is an ambiguous specification, and thus

ValueError: can only specify one unknown dimension

For all straightforward applications of reshape, `NumPy` does not actually create a new copy of an array’s data when performing a reshape operation. Instead, the original array and the reshaped array reference the same underlying data. The reshaped array simply provides a new index-interface for accessing said data, and is thus referred to as a “view” of the original array

### Matrix Operations ###

**Addition of Two Matrics**: We use `+` operator to add corresponding elements of two NumPy matrices.

In [ ]:
D1 = np.array([[2, 4], [5, -6]])
D2 = np.array([[9, -3], [3, 6]])
D = D1 + D2      # element wise addition
print(D)

[[11  1]
 [ 8  0]]


**Multiplication of Two Matrics** To multiply two matrices, we use `dot()` method. Learn more about how [numpy.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html) works.

In [ ]:
E1 = np.array([[3, 6, 7], [5, -3, 0]])
E2 = np.array([[1, 1], [2, 1], [3, -3]])
E = E1.dot(E2)
print(E)

[[ 36 -12]
 [ -1   2]]


On the other hand, as of Python 3.5, NumPy supports infix matrix multiplication using the
`@` operator, so you can achieve the same convenience of matrix multiplication with ndarrays in Python >= 3.5.

In [ ]:
print(E1 @ E2)

[[ 36 -12]
 [ -1   2]]


In contrast, numpy arrays consistently abide by the rule that operations are applied element-wise (except for the new `@` operator). Thus, 
if $A$ and $B$ are numpy arrays whose dimensions are the same, then $A*B$ is the array formed 
by multiplying the components element-wise:

In [ ]:
F1=np.array([[4, 3], [2, 1]])
F2=np.array([[1, 2], [3, 4]])
print(F1*F2)

[[4 6]
 [6 4]]


If $A$ is a matrix of type ndarray, then`A**2` returns an ndarray with each component squared element-wise. 

In [ ]:
print(F1**2)

[[16  9]
 [ 4  1]]


**Transpose of a Matrix** We use `numpy.transpose` to compute transpose of a matrix.

In [ ]:
G = np.array([[1, 1], [2, 1], [3, -3]])
print(G.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


### Access matrix elements, rows and columns ###

**Access matrix elements** Similar like lists, we can access matrix elements using index. Let's start with a one-dimensional NumPy array.

In [ ]:
H = np.array([2, 4, 6, 8, 10])

print("H[0] =", H[0])     # First element     
print("H[2] =", H[2])     # Third element 
print("H[-1] =", H[-1])   # Last element 

H[0] = 2
H[2] = 6
H[-1] = 10


Notice that the index starts from $0$. Now, let's see how we can access elements of a two-dimensional array (which is basically a matrix).

In [ ]:
M = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("M[0, 0] =", M[0,0])  
# Third element of second row
print("M[1, 2] =", M[1,2])

# Last element of last row
print("M[-1, -1] =", M[-1,-1])     

M[0, 0] = 1
M[1, 2] = 9
M[-1, -1] = 19


**Access rows of a Matrix** 

In [ ]:
print("M[0] =", M[0]) # First Row
print("M[2] =", M[2]) # Third Row
print("M[-1] =", M[-1]) # Last Row (3rd row in this case)

M[0] = [ 1  4  5 12]
M[2] = [-6  7 11 19]
M[-1] = [-6  7 11 19]


**Access columns of a Matrix**

In [ ]:
print("M[:,0] =",M[:,0]) # First Column
print("M[:,3] =", M[:,3]) # Fourth Column
print("M[:,-1] =", M[:,-1]) # Last Column (4th column in this case)

M[:,0] = [ 1 -5 -6]
M[:,3] = [12  0 19]
M[:,-1] = [12  0 19]


**Slicing of a Matrix** Slicing of a one-dimensional NumPy array is similar to a list. If you don't know how slicing for a list works, visit [Understanding Python's slice notation](https://stackoverflow.com/questions/509211/understanding-slice-notation).

In [ ]:
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        

# 1st to 6th elements
print(letters[:-1])           

# 6th to last elements
print(letters[5:])         

# 1st to last elements
print(letters[:])          

# reversing a list
print(letters[::-1])  

[5 7 9]
[1 3 5 7 9 7]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


Now, let's see how we can slice a matrix.

In [ ]:
print(M[:2, :4])  # two rows (row-0 and row-1), four columns (column-0 through column-3)
print(' ')

print(M[0,:])  # first row, all columns
print(' ')

print(M[:,2])  # all rows, third column
print(' ')

print(M[:, 2:5])  # all rows, third to fifth column

[[ 1  4  5 12]
 [-5  8  9  0]]
 
[ 1  4  5 12]
 
[ 5  9 11]
 
[[ 5 12]
 [ 9  0]
 [11 19]]


### N-dimensional Arrays ###

Let’s build up some intuition for arrays with a dimensionality higher than 2. The following code creates a 3-dimensional array:

In [ ]:
# a 3D array, shape-(2, 2, 2)
d3_array = np.array([[[0, 1],
                      [2, 3]],
                     [[4, 5],
                      [6, 7]]])
print(d3_array)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


**Depicting the layout of a 3D array**


   ![](img/3d_array.png) 
   
You can think of `axis-0` denoting which of the 2x2 “sheets” to select from. 
Then `axis-1` specifies the row along the sheets, and `axis-2` the column within the row.

Thus `d3_array[0,1,0]` specifies the element residing in sheet-0, at row-1 (second row) and column-0 (first column):

In [ ]:
# Retrieving a single element from a 3D array
ex1 = d3_array[0,1,0]
ex1

2

`d3_array[:, 0, 0]` specifies the elements in row-0 and column-0 of both sheets:

In [ ]:
# retrieving a 1D sub-array from a 3D-array
ex2 = d3_array[:,0,0]
ex2

array([0, 4])

`d3_array[1]`, which recall is shorthand for `d3_array[1, :, :]`, selects both rows and both columns of sheet-1:

In [ ]:
# retrieving a 2D sub-array from a 3D-array
ex3 = d3_array[1]
print(ex3)

[[4 5]
 [6 7]]


In four dimensions, one can think of “stacks of sheets with rows and columns” where axis-0 selects the stack of sheets you are working with, axis-1 chooses the sheet, axis-2 chooses the row, and axis-3 chooses the column. Extrapolating to higher dimensions (“collections of stacks of sheets …”) continues in the same tedious fashion.

###  Exercises ###

1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a 2D array of shape-(10,10) with 1 on the border and 0 inside.
3. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th elements?
4. Given the 3D, shape-(3,3,3) array:

   ![](img/nparray-pr1.png)
   
   Write a code of indexing into the array to produce the following results.   
     
    ![](img/nparray-pr1c.png) 
   

### NumPy Resources ###

As you can see, using NumPy (instead of nested lists) makes it a lot easier to work with matrices, and we haven't even scratched the basics. We suggest you to explore NumPy package in detail especially if you trying to use Python for data science/analytics.

 * [Quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)
 * [Numpy Array Basic A](https://www.bogotobogo.com/python/python_numpy_array_tutorial_basic_A.php)
  and [Numpy Array Basic B](https://www.bogotobogo.com/python/python_numpy_array_tutorial_basic_B.php)
 * [Numpy tutorial](http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html)
 * [NumPy Reference](https://docs.scipy.org/doc/numpy-1.14.5/reference/)